const state={dataset:location.pathname==='/demo'?'demo':'live',issues:[],selectedIssue:null,proposal:null,csrf:document.querySelector('meta[name="csrf-token"]').content};
const $=selector=>document.querySelector(selector);
async function api(path,options={}){const url=`${path}${path.includes('?')?'&':'?'}dataset=${state.dataset}`;const response=await fetch(url,{...options,headers:{'content-type':'application/json','x-csrf-token':state.csrf,...options.headers}});const data=await response.json();if(!response.ok)throw new Error(data.message||'Request failed');return data}
function el(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node}
function toast(message){const node=$('#toast');node.textContent=message;node.style.display='block';setTimeout(()=>node.style.display='none',2500)}
function filtered(){const query=$('#search').value.toLowerCase();const status=$('#status').value;return state.issues.filter(issue=>(!query||`${issue.title} ${issue.summary}`.toLowerCase().includes(query))&&(!status||issue.status===status))}
function renderIssues(){const root=$('#issue-list');root.replaceChildren();for(const issue of filtered()){const card=el('article',undefined,`issue-card${state.selectedIssue?.id===issue.id?' active':''}`);card.append(el('h3',issue.title),el('p',`${issue.uniqueAskers} học viên · ${issue.questionCount} câu · ${issue.status}`,'meta'));card.onclick=()=>loadIssue(issue.id);root.append(card)}}
async function loadIssue(id){state.selectedIssue=(await api(`/api/issues/${encodeURIComponent(id)}`)).issue;renderIssues();renderDetail()}
function button(label,handler){const node=el('button',label);node.type='button';node.onclick=handler;return node}
function renderDetail(){const root=$('#issue-detail');root.replaceChildren();const issue=state.selectedIssue;if(!issue){root.append(el('p','Chọn một issue để xem chi tiết.'));return}root.append(el('h2',issue.title),el('p',issue.summary,'muted'));const questions=el('section',undefined,'questions');for(const question of issue.questions){const row=el('label',undefined,'question');const box=document.createElement('input');box.type='checkbox';box.value=question.id;box.dataset.question='true';row.append(box,document.createTextNode(` ${question.text} · ${question.id}`));questions.append(row)}root.append(questions);if(state.dataset==='demo')return root.append(el('p','Dataset demo chỉ được xem.','muted'));const actions=el('div',undefined,'actions');actions.append(button('Phân tích bằng AI',analyze),button('Resolve',()=>mutate(`/api/issues/${encodeURIComponent(issue.id)}/resolve`,{})),button('Reopen',()=>mutate(`/api/issues/${encodeURIComponent(issue.id)}/reopen`,{})),button('Chuyển câu đã chọn',moveSelected),button('Merge issue',mergeIssue));if(issue.representativeJumpUrl){const link=el('a','Mở Discord');link.href=issue.representativeJumpUrl;link.target='_blank';link.rel='noreferrer';actions.append(link)}root.append(actions)}
async function mutate(path,body){await api(path,{method:'POST',body:JSON.stringify(body),headers:{origin:location.origin}});toast('Đã cập nhật');await loadAll()}
async function analyze(){state.proposal=(await api(`/api/issues/${encodeURIComponent(state.selectedIssue.id)}/analyze`,{method:'POST',body:'{}',headers:{origin:location.origin}})).proposal;renderProposal();$('#split-review').showModal()}
function renderProposal(){const root=$('#proposal-groups');root.replaceChildren();for(const group of state.proposal.groups){const card=el('section',undefined,'proposal');const title=document.createElement('input');title.value=group.title;title.dataset.key=group.key;title.dataset.field='title';card.append(title,el('p',`${group.questionIds.length} câu · confidence ${group.confidence}`,'meta'));for(const id of group.questionIds)card.append(el('p',id,'muted'));root.append(card)}}
$('#confirm-split').onclick=async()=>{const groups=[...document.querySelectorAll('[data-field="title"]')].map(input=>({key:input.dataset.key,title:input.value}));await mutate(`/api/issues/${encodeURIComponent(state.selectedIssue.id)}/split`,{proposalId:state.proposal.id,groups});$('#split-review').close()};
async function moveSelected(){const questionIds=[...document.querySelectorAll('[data-question]:checked')].map(input=>input.value);if(!questionIds.length)return toast('Chọn ít nhất một câu hỏi');const targetId=prompt('Issue ID đích; để trống nếu muốn tạo issue mới');if(targetId)return mutate('/api/questions/move',{sourceId:state.selectedIssue.id,targetId,questionIds});const title=prompt('Tên issue mới');if(title)await mutate('/api/questions/move',{sourceId:state.selectedIssue.id,questionIds,newIssue:{title,topics:state.selectedIssue.topics}})}
async function mergeIssue(){const targetId=prompt('Issue ID sẽ được giữ lại');if(targetId)await mutate('/api/issues/merge',{sourceId:state.selectedIssue.id,targetId})}
async function loadAll(){const data=await api('/api/issues');state.issues=data.issues;if(state.selectedIssue)state.selectedIssue=(await api(`/api/issues/${encodeURIComponent(state.selectedIssue.id)}`)).issue;renderIssues();renderDetail()}
for(const buttonNode of document.querySelectorAll('[data-dataset]'))buttonNode.onclick=()=>location.href=buttonNode.dataset.dataset==='demo'?'/demo':'/';$('#search').oninput=renderIssues;$('#status').onchange=renderIssues;loadAll().then(async()=>{const proposalId=new URLSearchParams(location.search).get('proposal');if(proposalId){state.proposal=(await api(`/api/split-proposals/${encodeURIComponent(proposalId)}`)).proposal;renderProposal();$('#split-review').showModal()}}).catch(error=>toast(error.message));
